-- 🗄️ Supabase BusGo Initial Schema

-- 1. Users Table (Already handled by Supabase Auth, but we link it)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Cities & Terminals
CREATE TABLE IF NOT EXISTS public.cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    country TEXT,
    terminal_name TEXT,
    location_coords GEOGRAPHY(POINT) -- Optional: for GPS tracking in V2
);

-- 3. Buses
CREATE TABLE IF NOT EXISTS public.buses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    plate_number TEXT,
    bus_type TEXT, -- 'VIP', 'Comfort', 'Economy'
    total_seats INTEGER NOT NULL,
    amenities JSONB DEFAULT '[]', -- ['wifi', 'power', 'tv', 'coffee']
    seat_map JSONB -- Internal layout definition
);

-- 4. Trips (Reyslar)
CREATE TABLE IF NOT EXISTS public.trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_id BIGINT REFERENCES public.buses(id),
    from_city_id BIGINT REFERENCES public.cities(id),
    to_city_id BIGINT REFERENCES public.cities(id),
    departure_time TIMESTAMPTZ NOT NULL,
    arrival_time TIMESTAMPTZ NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'ongoing', 'completed', 'cancelled'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Bookings (Joy band qilinishi)
CREATE TABLE IF NOT EXISTS public.bookings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    trip_id BIGINT REFERENCES public.trips(id),
    user_id UUID REFERENCES public.profiles(id),
    passenger_name TEXT NOT NULL,
    passenger_email TEXT,
    passenger_phone TEXT,
    seat_numbers TEXT[], -- Array of seat numbers
    total_price DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'cancelled'
    payment_id TEXT,
    qr_code_id TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Payments
CREATE TABLE IF NOT EXISTS public.payments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    booking_id UUID REFERENCES public.bookings(id),
    amount DECIMAL(10, 2) NOT NULL,
    currency TEXT DEFAULT 'USD',
    payment_method TEXT, -- 'Payme', 'Click', 'Stripe'
    transaction_id TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can view their own bookings" ON public.bookings
    FOR SELECT USING (auth.uid() = user_id);
